### ISSUE TITLE
Webgui - jquery error after upgrade from 23.7 to 24.1

### ISSUE THREAD

**Issue by hjr5203** [opnsense/core#7634]
Upgrade steps taken:
1. Made backup of config before doing the upgrade.
2. Use Dashboard upgrade path from the last version of 23.7 to 24.1
3. After completion, logged back into web interface and the Dashboard loaded but with no widgets and just the side menu. None of the menu options in the side menu work when clicking on any menu heading.
4. Completed the upgrade to 24.1.10 via the console
5. After completion, logged back into web interface and Dashboard still loads the same as in step 3 above. The same happens on different PC's and with 3 different browsers: Chrome, Firefox & Brave
6. When opening Developer Tools to check for any errors, the following jquery errors appears and the last error (reading 'split') keeps on repeating itself:

Uncaught TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> (index.php:100:36)
    at e (jquery-3.5.1.min.js:2:30005)
    at t (jquery-3.5.1.min.js:2:30307)
	
Uncaught TypeError: $(...).selectpicker is not a function
    at index.php:2534:46
    at Object.complete (opnsense.js?v=172af3050155f626:298:21)
    at c (jquery-3.5.1.min.js:2:28294)
    at Object.fireWith (jquery-3.5.1.min.js:2:29039)
    at l (jquery-3.5.1.min.js:2:79928)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2:82254)

Uncaught TypeError: Cannot read properties of undefined (reading 'getContext')
    at traffic_graph (index.php:2195:33)
    at index.php:2271:19
    at Object.complete (opnsense.js?v=172af3050155f626:298:21)
    at c (jquery-3.5.1.min.js:2:28294)
    at Object.fireWith (jquery-3.5.1.min.js:2:29039)
    at l (jquery-3.5.1.min.js:2:79928)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2:82254)
	
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at Object.<anonymous> (index.php:2429:73)
    at Function.each (jquery-3.5.1.min.js:2:2976)
    at index.php:2402:23
    at Object.complete (opnsense.js?v=172af3050155f626:298:21)
    at c (jquery-3.5.1.min.js:2:28294)
    at Object.fireWith (jquery-3.5.1.min.js:2:29039)
    at l (jquery-3.5.1.min.js:2:79928)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2:82254)
(anonymous) @ index.php:2429
each @ jquery-3.5.1.min.js:2
(anonymous) @ index.php:2402
complete @ opnsense.js?v=172af3050155f626:298
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
l @ jquery-3.5.1.min.js:2
(anonymous) @ jquery-3.5.1.min.js:2
load (async)
send @ jquery-3.5.1.min.js:2
ajax @ jquery-3.5.1.min.js:2
ajaxGet @ opnsense.js?v=172af3050155f626:290
fetch_services @ index.php:2394
setTimeout (async)
fetch_services @ index.php:2447
